spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: sanghyuphan
    password:

  # JPA properties
  jpa:
    show_sql: true # System out
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
